### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by ruslankhh** [yandex-shri-fx-team/mapsapi-polygonmap#16]
I think this name (mapsapi-blabla) does not clearly reflect the link to technology. It's unclear what kind of APIs are those maps: Google Maps, Mapbox, Leaflet, OSM, Yandex Maps? Before we publish this package to the NPM, we need to resolve this issue.

It seems to me better to do as here:
- [ymaps-stat-visualizer](https://github.com/twirl/ymaps-stat-visualizer)
- [ymaps-heatmap](https://github.com/zloylos/ymaps-heatmap)
- [ymaps-pie-chart-clusterer](https://github.com/yandex/ymaps-pie-chart-clusterer)
- [ymaps-touch-scroll](https://github.com/whooehoo/ymaps-touch-scroll)
- [ymaps-geo-motion](https://github.com/i4got10/ymaps-geo-motion)
- [ymaps-twitter](https://github.com/dmikis/ymaps-twitter)

**Comment by shackijj** [comment]
I agree.

**Comment by vit134** [comment]
i agree to
